// <auto-generated />
using System;
using GeoDoorServer3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeoDoorServer3.Migrations.UserDb
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20190510191843_migration1")]
    partial class migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("GeoDoorServer3.Models.DataModels.ConnectionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Message");

                    b.Property<DateTime>("MsgDateTime");

                    b.HasKey("Id");

                    b.ToTable("ConnectionLogs");
                });

            modelBuilder.Entity("GeoDoorServer3.Models.DataModels.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LogLevel");

                    b.Property<string>("Message");

                    b.Property<DateTime>("MsgDateTime");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("GeoDoorServer3.Models.DataModels.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("UserConnectionPort");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("GeoDoorServer3.Models.DataModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessRights");

                    b.Property<DateTime>("LastConnection");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneId");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
